/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#00714d",
        "primary-fixed": "#d8e2ff",
        "on-surface": "#191b23",
        "on-secondary": "#ffffff",
        "surface-container": "#ecedf7",
        "inverse-primary": "#adc6ff",
        "surface-container-highest": "#e1e2ec",
        "primary-container": "#2170e4",
        "error": "#ba1a1a",
        "background": "#f9f9ff",
        "on-secondary-fixed-variant": "#005236",
        "surface-container-high": "#e6e7f2",
        "tertiary-fixed": "#ffdcc6",
        "tertiary-container": "#b75b00",
        "inverse-surface": "#2e3038",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#4edea3",
        "inverse-on-surface": "#eff0fa",
        "on-tertiary-fixed": "#311400",
        "outline": "#727785",
        "surface-dim": "#d8d9e3",
        "on-primary-fixed": "#001a42",
        "on-tertiary-container": "#fffbff",
        "secondary-fixed": "#6ffbbe",
        "on-error-container": "#93000a",
        "tertiary": "#924700",
        "on-tertiary": "#ffffff",
        "secondary-container": "#6cf8bb",
        "on-tertiary-fixed-variant": "#723600",
        "surface-tint": "#005ac2",
        "surface-variant": "#e1e2ec",
        "surface-container-low": "#f2f3fd",
        "on-primary-container": "#fefcff",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#002113",
        "primary-fixed-dim": "#adc6ff",
        "on-primary-fixed-variant": "#004395",
        "on-primary": "#ffffff",
        "outline-variant": "#c2c6d6",
        "surface-bright": "#f9f9ff",
        "surface": "#f9f9ff",
        "error-container": "#ffdad6",
        "secondary": "#006c49",
        "primary": "#0058be",
        "tertiary-fixed-dim": "#ffb786",
        "on-background": "#191b23",
        "on-surface-variant": "#424754",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "IBM Plex Sans Arabic"],
        "body": ["Be Vietnam Pro", "Tajawal"],
        "label": ["Be Vietnam Pro", "Tajawal"],
      },
      boxShadow: {
        "header": "0 12px 40px rgba(25, 27, 35, 0.06)",
        "card": "0 4px 20px rgba(0, 0, 0, 0.02)",
      },
    },
  },
  plugins: [],
};